// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJZubpebhcq7jCvlBfMBjBxYwFCUHhJQ',
    appId: '1:851270828429:web:ac32040248bf831b987dc4',
    messagingSenderId: '851270828429',
    projectId: 'quest-tara',
    authDomain: 'quest-tara.firebaseapp.com',
    storageBucket: 'quest-tara.firebasestorage.app',
    measurementId: 'G-Z13EXY62JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb5TrNmh89jA_LysS1T1tK7p3EBTlX-Vs',
    appId: '1:851270828429:android:0e9097ebe0847d97987dc4',
    messagingSenderId: '851270828429',
    projectId: 'quest-tara',
    storageBucket: 'quest-tara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIA8iemSGocoVe4TW_JLCgtGQb9jfnlY',
    appId: '1:851270828429:ios:8946c1013a5a7772987dc4',
    messagingSenderId: '851270828429',
    projectId: 'quest-tara',
    storageBucket: 'quest-tara.firebasestorage.app',
    iosBundleId: 'com.example.campusAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFIA8iemSGocoVe4TW_JLCgtGQb9jfnlY',
    appId: '1:851270828429:ios:8946c1013a5a7772987dc4',
    messagingSenderId: '851270828429',
    projectId: 'quest-tara',
    storageBucket: 'quest-tara.firebasestorage.app',
    iosBundleId: 'com.example.campusAppMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKJZubpebhcq7jCvlBfMBjBxYwFCUHhJQ',
    appId: '1:851270828429:web:63ca02708e941885987dc4',
    messagingSenderId: '851270828429',
    projectId: 'quest-tara',
    authDomain: 'quest-tara.firebaseapp.com',
    storageBucket: 'quest-tara.firebasestorage.app',
    measurementId: 'G-Z47JRQVKSN',
  );
}
